steps:
  - name: 'gcr.io/cloud-builders/docker'
    args:
      [
        'build',
        '-t',
        'europe-west1-docker.pkg.dev/$PROJECT_ID/cloud-run-source-deploy/salonkee-salons-etl:$COMMIT_SHA',
        '.'
      ]

  - name: 'gcr.io/cloud-builders/docker'
    args:
      [
        'push',
        'europe-west1-docker.pkg.dev/$PROJECT_ID/cloud-run-source-deploy/salonkee-salons-etl:$COMMIT_SHA'
      ]

  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args:
      [
        'run', 'jobs', 'update', 'salonkee-salons-etl',
        '--image', 'europe-west1-docker.pkg.dev/$PROJECT_ID/cloud-run-source-deploy/salonkee-salons-etl:$COMMIT_SHA',
        '--region', 'europe-west1',
        '--set-env-vars', 'TABLE_ID=cpb-data-platform-prod.cpb_raw.salonkee_salons,API_URL=https://salonkee.be/api/web-services/v1/salons',
        '--set-secrets', 'API_TOKEN=API_TOKEN:latest'
      ]
images:
  - 'europe-west1-docker.pkg.dev/$PROJECT_ID/cloud-run-source-deploy/salonkee-salons-etl:$COMMIT_SHA'